# Generated by Django 4.2.4 on 2025-07-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_trial",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="trial_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
