# Generated by Django 4.2.4 on 2025-07-14 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "subscriptions",
            "0002_payment_remove_subscriber_email_subscriber_mobile_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="user",
        ),
        migrations.AddField(
            model_name="payment",
            name="subscriber",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="subscriptions.subscriber",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscriber",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="payment",
            name="plan_id",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="payment",
            name="razorpay_order_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="payment",
            name="razorpay_payment_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="payment",
            name="razorpay_signature",
            field=models.CharField(max_length=255),
        ),
    ]
