# Generated by Django 4.2.4 on 2025-07-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_businessprofile_alter_menuitem_business_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessprofile",
            name="business_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
